name: Build Android Globed Mod

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: geode-sdk/build-geode-mod@v1
        id: build
        with:
          target: Android64

      - uses: actions/upload-artifact@v4
        with:
          name: globed-android64
          path: ${{ steps.build.outputs.build-output }}


